db/institutions.yml

Sometimes people use the verbose name for the university

ENH: added city of new york to columbia aka

---

db/institutions.yml

MNT: Add ESRF info to institutions.yml

---

db/institutions.yml

FIX: Added University of Washington to institutions db

---

db/institutions.yml

added simon institutions

---

db/groups.yml
db/institutions.yml
db/people.yml

migrated the institutions db to new format.  I hope it is the right format!

Schools to dicts

---

db/institutions.yml

DOC: add U of Toronto

---

db/institutions.yml

Add queen mary college

---

db/institutions.yml
get_uni.py

This adds a bunch of universities in the USA (and a good mechanism for more). Note that this doesn't add the departments or schools. The CSV that this is based on doesn't capture those.

ENH: add a bunch of universities (no departments/schools though)

---

db/institutions.yml

DOC: add U Montreal

---

db/institutions.yml

Add Tsinghua University

---

db/institutions.yml

ENH: Add entry for UNAM

---

db/institutions.yml

DOC: add  cornell entry

---

db/institutions.yml

ENH: Add entry for Pune University Physics

---

db/institutions.yml

Add Ghent University

---

db/institutions.yml

ENH: Added entry for University of Belgrade

---

db/institutions.yml

DOC: add ASU

---

db/institutions.yml

ENH: Add Drexel University

---

db/institutions.yml

redo edits in PR #77 , and submit PR again. Close Issue #61.

ENH: Add Addis Ababa University, Ethiopia

---

db/institutions.yml

DOC: add vanderbilt

---

db/institutions.yml

add bayreuth

---

db/institutions.yml

British drug cos

---

db/people.yml

"stao" is added to db/people.yml with ORCID-ID.

add_stao_to_people

---

db/institutions.yml

@sbillinge this is ready for review

added physics to Ohio U

---

db/institutions.yml
db/people.yml

Add delaware

---

db/people.yml

Tim add ACA award

---

db/people.yml

I added myself at the end of the people.yml file.
Hung

people.yml modified.

---

db/people.yml

@sbillinge this is working progress, I still need to update bio. I will let you know when it is ready for review.

added sani to people

---

db/people.yml

@sbillinge this is making Rohan Active.  This should be ready for reveiw and merge

change Rohan avatar

---

db/citations.yml

cleaning recent citations and adding theses

cleaning recent citations, adding theses

---

db/people.yml

adding epdic award

---

db/people.yml

Hopefully I updated my profile.... still getting used to this

updated my bio

---

db/institutions.yml
db/people.yml

This reverts commit 6c9a25d793529160dbdb93f92b9139ff463ebd7f.

Revert "Revert "adding aka's to people""

---

db/citations.yml

update two international table vol. H  entries in `citations.yml`

update itoch18 entries

---

db/citations.yml

For re-submission checklist.
Update the author list by adding Matt Tucker.

MAINT: update structure mining author list

---

db/citations.yml

WARNING: terba;ic17 is missing month
WARNING: urban;nan17 is missing month
WARNING: anaso;nh16 is missing month
WARNING: beech;acsel16 is missing month
WARNING: bozin;nn16 is missing month
WARNING: choi;nan16 is missing month
WARNING: dippe;aca16 is missing month
WARNING: duxbu;4or16 is missing month
WARNING: duxbu;asilomar16 is missing month
WARNING: duxbu;dam16 is missing month
WARNING: frand;nc16 is missing month
WARNING: frand;nn16 is missing month
WARNING: frand;prb16 is missing month
WARNING: guguc;prb16 is missing month
WARNING: jense;nc16 is missing month
WARNING: miao;s16 is missing month
WARNING: scard;aca16 is missing month
WARNING: shatn;prb16 is missing month
WARNING: terba;macm16 is missing month

added months - Issue #187

---

db/institutions.yml

changed uiuc

---

db/citations.yml

missing months

---

db/institutions.yml

Add intst0216 1

---

db/institutions.yml

newcastle added

---

db/institutions.yml

@sbillinge the other two entries passed the test but they are under separate pull requests. I am making this one as a separate pull request as well but for the rest could you remind me how to pile them under one pull request?

added umichigan

---

db/institutions.yml

added institutions from A-M

---

db/institutions.yml

nmaist added

---

db/institutions.yml
db/people.yml

@sbillinge this is ready for review and merge

Add martin to people

---

db/institutions.yml

updated the four first institutions from my list

---

db/institutions.yml

sophiau added

---

.gitignore
db/institutions.yml

@sbillinge Hello, Simon. I add the institutions of the new citation. I also change a little bit of the new_institution.py so that it can add departments and schools.

Add citation

---

db/people.yml

@sbillinge 
I could not find information about II-Kyounh Jeong, He Lin, Hyunjeong Kim, and Ahmad Masadeh. Also could not find information about the position and when Timur Dykhne started working at Samsung. I am committing to see if there are necessary changes for the ones that I found information. I am going to keep looking for the others.

Addgradstudents

---

db/people.yml

added Yarong Lin

---

db/citations.yml

@sbillinge , this PR updates the place of publication on your books. Please review and merge.

MAINT: update book publication place

---

db/people.yml

Kevin Knox re-added to new pr

---

db/people.yml

Chris Farrow added

---

db/institutions.yml

uminnesota added

---

db/people.yml

Passed locally. Work in progress.

added Gianluca Paglia

---

db/people.yml

added Thomas Proffen

---

db/people.yml

I am working on this, don't merge yet

adding former visitor students

---

db/people.yml

Wenduo Zhou added

---

db/people.yml

First pull request to update career and education information in db/people.yml

Updated Work and Education History for ZThatcher

---

db/people.yml

@sbillinge I updated my avatar, please merge!

updated Daniela's avatar

---

db/people.yml

Updated my picture, could you please merge.

added avatar to Berrak Ozer

---

db/people.yml

New Pull Request because of merging problems.

readded Jiwu Liu on new branch

---

db/people.yml

@sbillinge I updated my resume

Ran update his resume

---

db/citations.yml

@st3107 @sbillinge , please review and merge. I updated the citation info with published paper version.

add published info for strumining paper

---

db/people.yml

Made some updates to the people.yml file to add my information

updated bio and avatar

---

db/people.yml

update bio and education information

update bio and education_Jiawei

---

db/people.yml

Only change lines 1537 to 1565.

Jaylyn C. Umana profile update

---

db/people.yml

I have updated my people.yml entry.

Updated Ahmed's entry in projecta.yml

---

db/people.yml

added my bio, aka, education, and GitHub id  in the public people database

updated Adiba's entry in people database

---

db/people.yml

ZTUpdateOrcidGITHubID

---

db/people.yml

hi professor @sbillinge !
I added my GitHub_id and updated some info!

Added GitHub, changes bio and date

---

db/people.yml

Added Vivian Github ID

---

db/people.yml

Hi, @sbillinge Ready to merge.

People: add github_id

---

db/people.yml

Hi Simon,
Please review and merge this!
Hung

Added github id.

---

db/people.yml

Google scholar URL added to people collection

ZTScholarURL

---

db/institutions.yml
db/people.yml

@CJ-Wright @sbillinge 
I've updated my bio, education, and avatar. Only my info in people.yml is modified.

Updated people.yml with my bio and more

---

db/people.yml

Does this formatting look right?
If it does, then I just had to do a 'save without formatting'

add eric to people

---

db/citations.yml

@sbillinge , please review and merge. Add the accepted organic MXene paper, will be publishing on Chem. Mater.

ENH: add the submitted organic MXene paper citations

---

db/people.yml

I added information to people.yml.

Updated personal information, people.yml

---

db/citations.yml

Hi @sbillinge , I added the arxiv entry for MgTi2O4 paper, please review and merge.

ENH: add MTO paper in arxiv

---

db/citations.yml

@sbillinge , please review and merge

add pdfitc citation entry

---

db/citations.yml

@sbillinge , please review and merge. I added the published info for the organic MXene paper.

MAINT: add published info for organic mxene entry

---

db/citations.yml

@sbillinge , I updated the PDFitc citation with the newest info. Please review and merge.

MAINT: update pdfitc citation

---

db/citations.yml

@sbillinge , please review and merge.

update mgti2o4 paper with published info

---

db/citations.yml

@sbillinge , Please review and merge.
BTW, I also updated a few published info about the PDFitc paper citation in the same PR.

Mto paper published

---

db/people.yml

Updated my personal info in People db

Yevgeny updated people

---

db/citations.yml

Ran create citation item

---

db/citations.yml

Hi @sbillinge 
I added arxiv information to the citation. please merge

fill arxiv info

---

db/people.yml

Realized I never updated my people.yml info. This PR contains my updated info.

Adding Connor Bracy to people.

---

db/people.yml

@sbillinge - Jason's section in people.yml has been updated. I could not find a proper profile picture of myself yet so I'll leave the avatar entry like this for the moment. I also updated my GitHub username and changed from "masters researcher" to "graduate research assistant".

Adding Jason to people

---

db/citations.yml

I add the missing doi for the publications.

add missing doi

---

db/people.yml

adding my bio, education, and avatar to people.yml

Updating people.yml with my info

---

db/people.yml

I'm not sure if that's the correct way to add a 2nd line for a 2nd degree, if it's not let me know.

updated information on people for cbullard

---

db/people.yml

@sbillinge: ready for review and merge.

updated avatar

---

db/institutions.yml
db/people.yml

Dear Prof. Simon Billinge,
This is an update of my bio, aka and education.
BW,
Fengkai Wei

Add my name

---

db/people.yml

Hi!! I updated my Bio! Thanks to Songsheng

Max Updated Bio

---

db/people.yml

add_qiang_du

---

db/people.yml

second attempt at adding my profile to people.yml. Not sure why it wouldn't trigger the CI earlier, we'll see if it does this time

adding ryan with bio to people.yml

---

db/presentations.yml

adding job interviews

---

db/citations.yml

Hi @sbillinge , this is the same as my PR in the group repo. I have changed the link in the citation yaml file.

ling change link

---

.travis.yml

@sbillinge, this should fix the issue of the CI failing

Fixing .travis.yml to accommodate recent GitHub clone protocol changes

---

db/people.yml

updated Kevin's bio, education, and avatar

updated bio, education, and avatar

---

db/people.yml

Started from scratch because I was running into problems with the other PR.

adding kayla to people

---

.github/workflows/main.yml
.github/workflows/publish.yml

This PR is a branch from within `Billingegroup` *NOT* my fork!!

Recommitting missing updates to main.yaml and publish.yaml

---

db/people.yml

Nothing was added in bio/edu as it seems that other recent group members did not fill that out

University was corrected to Aarhus

---

db/people.yml

created a new local branch and branch on my origin named "bio"
Added education and bio to the aajayi profile

completing aajayi bio

---

db/people.yml

I just added myself to people.yml. Sorry for the delay.

added sean to people.yml file

---

db/people.yml

Good morning Simon,
I hope you are well.
Please have a look at the entries for iadnan in 'People.yml'. I believe everything is filled in. However, If I happened to miss something specific, please let me know and I will amend it.
As I have just created my orcid account, it is pretty much empty. With that said, I will definitely add further information whenever I get to it.
Thanks in advance,
Ibrahim

Adding iadnan to People.yml

---

db/people.yml

onboarding task - I edited my info on db/people.yml to include my bio and education

edit tnanarong bio and education

---

db/citations.yml
db/institutions.yml
db/people.yml
db/presentations.yml

- adding Jack paper to citations
- adding afls presentation
- some activities for simon

sjb updates

---

db/citations.yml

add arxiv link and corrected previous errors (empty strings). We can merge this one and ignore the previous PR.

Tina paper 2

---

db/citations.yml

Hi @sbillinge , the citation db is updated by adding the sbm paper. After the paper is accepted and published, I will update the db again by adding the doi and so on. Thx!

ling add citation for sbm paper

---

db/citations.yml
db/people.yml
db/presentations.yml

- update journal, DOI, publication month and year in citations.yml 
- pre-commit also changed other files (mostly removed trailing whitespaces)

edit citation for Tina's npj paper
